{% set name = "respondo" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gator-program/respondo/archive/v{{ version }}.tar.gz
  sha256: 6986efafcef0e25d772031fa0cdc464c126864b0ea59c53aba1470a21685152d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.14
    - adcc >=0.15.14

test:
  imports:
    - respondo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gator-program/respondo
  summary: Library for evaluating response functions for molecular properties
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apapapostolou
    - maxscheurer
