{% set name = "respondo" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gator-program/respondo/archive/v{{ version }}.tar.gz
  sha256: e552b641176675b5e7cba693935d45ac67e7e925027472273b045c17b1b35d12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.14
    - adcc >=0.15.14

test:
  imports:
    - respondo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gator-program/respondo
  summary: 'Library for evaluating response functions for molecular properties'
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apapapostolou
    - maxscheurer
