context:
  name: respondo
  version: 0.0.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/gator-program/respondo/archive/v${{ version }}.tar.gz
  sha256: da8d13a533140f7d249665ce32e69a35b6e151fda51542baab07be0e0213334f

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - versioningit >=2.0,<3.dev0
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.14
    - adcc >=0.16.0

tests:
  - python:
      imports:
        - respondo
      python_version: ${{ python_min }}.*
  - script:
      - pip check
    requirements:
      run:
        - pip

about:
  homepage: https://github.com/gator-program/respondo
  summary: Library for evaluating response functions for molecular properties
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apapapostolou
    - maxscheurer
